"""empty message

Revision ID: 14ff8d769775
Revises: f0ced4f04972
Create Date: 2024-05-02 23:24:10.035607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ff8d769775'
down_revision: Union[str, None] = 'f0ced4f04972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('start_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'start_count')
    # ### end Alembic commands ###
