"""empty message

Revision ID: 34971689d3dc
Revises: 0e298aec7925
Create Date: 2024-04-17 16:23:15.310254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34971689d3dc'
down_revision: Union[str, None] = '0e298aec7925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('likes_count', sa.Integer(), nullable=False))
    op.drop_column('comments', 'like_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('like_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('comments', 'likes_count')
    # ### end Alembic commands ###
