"""empty message

Revision ID: 3b340ed9c381
Revises: 
Create Date: 2024-01-30 18:50:10.527505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b340ed9c381'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('age_rating_games', 'game_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('age_rating_games', 'age_rating_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('unique_age', 'age_rating_games', type_='unique')
    op.create_unique_constraint('_age_rating_game_uc', 'age_rating_games', ['game_id', 'age_rating_id'])
    op.drop_constraint('age_rating_games_game_id_fkey', 'age_rating_games', type_='foreignkey')
    op.drop_constraint('age_rating_games_age_rating_id_fkey', 'age_rating_games', type_='foreignkey')
    op.create_foreign_key(None, 'age_rating_games', 'age_ratings', ['age_rating_id'], ['id'])
    op.create_foreign_key(None, 'age_rating_games', 'games', ['game_id'], ['id'])
    op.alter_column('age_ratings', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint('age_ratings_type_key', 'age_ratings', type_='unique')
    op.alter_column('game_genres', 'game_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('game_genres', 'genre_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('unique_genre', 'game_genres', type_='unique')
    op.create_unique_constraint('_game_genre_uc', 'game_genres', ['game_id', 'genre_id'])
    op.drop_constraint('game_genres_game_id_fkey', 'game_genres', type_='foreignkey')
    op.drop_constraint('game_genres_genre_id_fkey', 'game_genres', type_='foreignkey')
    op.create_foreign_key(None, 'game_genres', 'games', ['game_id'], ['id'])
    op.create_foreign_key(None, 'game_genres', 'genres', ['genre_id'], ['id'])
    op.alter_column('game_platforms', 'game_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('game_platforms', 'platform_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('unique_platform', 'game_platforms', type_='unique')
    op.create_unique_constraint('_game_platform_uc', 'game_platforms', ['game_id', 'platform_id'])
    op.drop_constraint('game_platforms_platform_id_fkey', 'game_platforms', type_='foreignkey')
    op.drop_constraint('game_platforms_game_id_fkey', 'game_platforms', type_='foreignkey')
    op.create_foreign_key(None, 'game_platforms', 'platforms', ['platform_id'], ['id'])
    op.create_foreign_key(None, 'game_platforms', 'games', ['game_id'], ['id'])
    op.drop_constraint('game_reviews_game_id_fkey', 'game_reviews', type_='foreignkey')
    op.drop_constraint('game_reviews_user_id_fkey', 'game_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'game_reviews', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'game_reviews', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('genres', 'code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('genres_name_key', 'genres', type_='unique')
    op.alter_column('platforms', 'platform_name_ru',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('platforms', 'code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('platforms_platform_name_key', 'platforms', type_='unique')
    op.drop_constraint('platforms_platform_slug_key', 'platforms', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('platforms_platform_slug_key', 'platforms', ['platform_slug'])
    op.create_unique_constraint('platforms_platform_name_key', 'platforms', ['platform_name'])
    op.alter_column('platforms', 'code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('platforms', 'platform_name_ru',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint('genres_name_key', 'genres', ['name'])
    op.alter_column('genres', 'code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'game_reviews', type_='foreignkey')
    op.drop_constraint(None, 'game_reviews', type_='foreignkey')
    op.create_foreign_key('game_reviews_user_id_fkey', 'game_reviews', 'users', ['user_id'], ['id'])
    op.create_foreign_key('game_reviews_game_id_fkey', 'game_reviews', 'games', ['game_id'], ['id'])
    op.drop_constraint(None, 'game_platforms', type_='foreignkey')
    op.drop_constraint(None, 'game_platforms', type_='foreignkey')
    op.create_foreign_key('game_platforms_game_id_fkey', 'game_platforms', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('game_platforms_platform_id_fkey', 'game_platforms', 'platforms', ['platform_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('_game_platform_uc', 'game_platforms', type_='unique')
    op.create_unique_constraint('unique_platform', 'game_platforms', ['game_id', 'platform_id'])
    op.alter_column('game_platforms', 'platform_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('game_platforms', 'game_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'game_genres', type_='foreignkey')
    op.drop_constraint(None, 'game_genres', type_='foreignkey')
    op.create_foreign_key('game_genres_genre_id_fkey', 'game_genres', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('game_genres_game_id_fkey', 'game_genres', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('_game_genre_uc', 'game_genres', type_='unique')
    op.create_unique_constraint('unique_genre', 'game_genres', ['game_id', 'genre_id'])
    op.alter_column('game_genres', 'genre_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('game_genres', 'game_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint('age_ratings_type_key', 'age_ratings', ['type'])
    op.alter_column('age_ratings', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'age_rating_games', type_='foreignkey')
    op.drop_constraint(None, 'age_rating_games', type_='foreignkey')
    op.create_foreign_key('age_rating_games_age_rating_id_fkey', 'age_rating_games', 'age_ratings', ['age_rating_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('age_rating_games_game_id_fkey', 'age_rating_games', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('_age_rating_game_uc', 'age_rating_games', type_='unique')
    op.create_unique_constraint('unique_age', 'age_rating_games', ['game_id', 'age_rating_id'])
    op.alter_column('age_rating_games', 'age_rating_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('age_rating_games', 'game_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
