"""empty message

Revision ID: 533c2edd9ba2
Revises: a3435d61d33f
Create Date: 2024-02-24 14:41:21.881566

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '533c2edd9ba2'
down_revision: str | None = 'a3435d61d33f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('walls', 'disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('walls', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
