"""empty message

Revision ID: 921e188b7224
Revises: 5ddbcd7013e4
Create Date: 2024-07-09 15:08:08.285778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921e188b7224'
down_revision: Union[str, None] = '5ddbcd7013e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('user_roles', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.drop_column('users', 'disabled')
    op.drop_column('users', 'is_moderator')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_moderator', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user_roles', 'updated_at')
    op.drop_column('user_roles', 'created_at')
    # ### end Alembic commands ###
