"""empty message

Revision ID: a3435d61d33f
Revises: 
Create Date: 2024-02-18 16:13:22.688623

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'a3435d61d33f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
