"""empty message

Revision ID: b4990cbc8464
Revises: 41b903a19412
Create Date: 2024-05-14 20:27:02.800899

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b4990cbc8464'
down_revision: Union[str, None] = '41b903a19412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pictures', 'posts', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pictures', type_='foreignkey')
    # ### end Alembic commands ###
