"""empty message

Revision ID: d79f52bd2a26
Revises: 533c2edd9ba2
Create Date: 2024-02-24 14:56:57.477741

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd79f52bd2a26'
down_revision: str | None = '533c2edd9ba2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'parent_post_id', existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'parent_post_id', existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
