"""empty message

Revision ID: db2ac1d56959
Revises: deeecfa3a515
Create Date: 2024-04-17 12:54:45.093043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db2ac1d56959'
down_revision: Union[str, None] = 'deeecfa3a515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_parent_comment_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'comments', ['parent_comment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(
        'comments_parent_comment_id_fkey', 'comments', 'comments', ['parent_comment_id'], ['id'], ondelete='RESTRICT'
    )
    # ### end Alembic commands ###
