"""empty message

Revision ID: db6a4423f0c0
Revises: b4990cbc8464
Create Date: 2024-05-15 11:35:54.312908

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'db6a4423f0c0'
down_revision: Union[str, None] = 'b4990cbc8464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pictures_item_id_fkey', 'pictures', type_='foreignkey')
    op.create_foreign_key(None, 'pictures', 'posts', ['item_id'], ['id'], ondelete='CASCADE')
    op.alter_column('posts', 'text', existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'text', existing_type=sa.VARCHAR(), nullable=False)
    op.drop_constraint(None, 'pictures', type_='foreignkey')
    op.create_foreign_key('pictures_item_id_fkey', 'pictures', 'posts', ['item_id'], ['id'])
    # ### end Alembic commands ###
