"""empty message

Revision ID: e5ce80b5b720
Revises: 
Create Date: 2024-02-02 17:00:25.207786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5ce80b5b720'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('game_genres_game_id_fkey', 'game_genres', type_='foreignkey')
    op.create_foreign_key(None, 'game_genres', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('_user_activity_uc', 'user_activity', type_='unique')
    op.create_unique_constraint('_user_activity_uc', 'user_activity', ['user_id', 'game_id', 'activity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_activity_uc', 'user_activity', type_='unique')
    op.create_unique_constraint('_user_activity_uc', 'user_activity', ['user_id', 'game_id'])
    op.drop_constraint(None, 'game_genres', type_='foreignkey')
    op.create_foreign_key('game_genres_game_id_fkey', 'game_genres', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###
