"""empty message

Revision ID: e9ba5393b51b
Revises: 12f06dc049ce
Create Date: 2024-02-25 10:08:03.669683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ba5393b51b'
down_revision: Union[str, None] = '12f06dc049ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playlists', 'about',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playlists', 'about',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
