"""empty message

Revision ID: e9ba5393b51b
Revises: 12f06dc049ce
Create Date: 2024-02-25 10:08:03.669683

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e9ba5393b51b'
down_revision: str | None = '12f06dc049ce'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playlists', 'about', existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playlists', 'about', existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
