"""empty message

Revision ID: f0ced4f04972
Revises: 889400379e85
Create Date: 2024-05-02 22:16:57.895521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ced4f04972'
down_revision: Union[str, None] = '889400379e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_activity_game_id_fkey', 'user_activity', type_='foreignkey')
    op.create_foreign_key(None, 'user_activity', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_activity', type_='foreignkey')
    op.create_foreign_key('user_activity_game_id_fkey', 'user_activity', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###
